update set-env-secrets to work with single-valued secrets under a host path

diff --git a/bin/set-env-secrets b/bin/set-env-secrets
--- a/bin/set-env-secrets
+++ b/bin/set-env-secrets
@@ -1,10 +1,26 @@
 #!/usr/bin/env bash
 
+# Preqequisites:
+#   - jq is installed and on the path
+#   - lpass is installed and on the path
 # Required environment variables:
 #   HOSTNAME
 #   LASTPASS_USERNAME
 
 error=
+
+# verifies that any dependency programs/scripts are installed
+function check_dependencies {
+  if ! command -v jq >/dev/null 2>&1; then
+    error="[check_dependencies] Missing required dependency: jq is not installed"
+    return 1
+  fi
+
+  if ! command -v lpass >/dev/null 2>&1; then
+    error="[check_dependencies] Missing required dependency: lpass is not installed"
+    return 1
+  fi
+}
 
 # verifies that required environment variables are set
 function check_environment {
@@ -24,25 +40,50 @@ function ensure_authentication {
   fi
 }
 
+# Retrieve env content, which consists of zero or more lines. Each line is a variable in the
+# form of "<NAME>=$(echo -n "<BASE64_ENCODED_VALUE>" | base64 -d)". 
+function get_env_content {
+  # get JSON string for all passwords with the specified path
+  envJson=$(
+    lpass show "automation\\hosts\\${HOSTNAME}\\.env" 2>/dev/null\
+      --fixed-strings \
+      --expand-multi \
+      --json
+  )
+
+  # if no passwords exist at that path, just set to an empty array
+  if [[ $? != 0 ]]; then
+    envJson="[]"
+  fi
+
+  echo "$envJson" | jq -r '.[] | "\(.name)=$(echo -n \"\(.note|@base64)\" | base64 -d)"'
+}
+
+if ! check_dependencies; then
+  echo "${error}" 1>&2
+  echo "Unable to fetch environment secrets." 1>&2
+  return 2
+fi
+
 if ! check_environment; then
   echo "${error}" 1>&2
   echo "Unable to fetch environment secrets." 1>&2
-  exit 1
+  return 1
 fi
 
 if ! ensure_authentication; then
   echo "${error}" 1>&2
   echo "Unable to fetch environment secrets." 1>&2
-  exit 2
+  return 2
 fi
 
-mapfile -t variables < <(fetch-secret --key "automation/hosts/${HOSTNAME}/.env")
+mapfile -t variables < <(get_env_content)
 for variable in "${variables[@]}"; do
-  export "$variable"
+  name=${variable%%=*}
+  echo "Setting: ${name}"
+  eval "export \"$variable\""
 done
 
-
--- todo 
-- do not fail if the host does not have env secrets
-- allow for project env secrets
-- allow for user env secrets
+# -- todo 
+# - allow for project env secrets
+# - allow for user env secrets
